telemetry = false
logLevel = "debug"
preload = []
smol = false

jsx = "react"
jsxFactory = "h"
jsxFragment = "Fragment"
jsxImportSource = "react"

[loader]
".cb" = "file"

[define]
"process.env.NODE_ENV" = "development"

[test]
coverageThreshold = { lines = 0.75, statements = 0.75, function = 0.75 }
coverage = true
coverageDir = "coverage"
coveragePathIgnorePatterns = []
coverageReporter = ["lcov", "text"]
coverageSkipTestFiles = false

[run]
bun = true
shell = "bun"
silent = false

[install]
saveTextLockfile = true
optional = false
dev = true
production = false
peer = true
frozenLockfile = false
linker = "hoisted"
auto = "auto"
